$kind: http-example
request:
  url: "{{baseUrl}}/api/v1/settings/public"
  method: GET
  headers:
    - key: Accept
      value: application/json
    - key: X-Api-Key
      value: <API Key>
      description: "Added as a part of security scheme: apikey"
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": true,
        "message": "Settings fetched successfully",
        "data": {
          "site_name": "TatkalDoctor",
          "support_email": "support@tatkaldoctor.com"
        }
      }
order: 1000
